name: $(Build.BuildId).$(Year:yy)$(DayOfYear)

trigger:
- master

resources:
  repositories:
    - repository: templates
      type: git
      name: Audacia/Audacia.Build.Templates
      
stages:

- stage: Build
  displayName: Build
  jobs:
    - template: jobs/build/netcore/signed-package.yaml@templates

- stage: Release
  displayName: Release
  jobs:
    - template: jobs/release/netcore/public-package.yaml@templates
