name: $(Build.BuildId).$(Year:yy)$(DayOfYear)

trigger:
- master
- develop
- dev

pool:
  vmImage: 'vs2017-win2016'
  
resources:
  repositories:
    - repository: templates
      type: git
      name: Audacia/Audacia.Build.Templates
      
steps:
- template: build-package.netcore.yaml@templates
